### ISSUE TITLE
IDA crash in struct members 

### ISSUE THREAD

**Issue by mahaloz** [angr/binsync#107]
Version: 2.1.0
```
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/ida_binsync/hooks.py", line 62, in initcheck
    return f(self, *args, **kwargs)
  File "/Applications/IDA Pro 7.7/ida64.app/Contents/MacOS/plugins/ida_binsync/hooks.py", line 203, in struc_member_renamed
    stack_var_info = compat.get_func_stack_var_info(func_addr)[mptr.soff]
KeyError: 24
```

BinSync Repo: https://github.com/mahaloz/dreamland
Platform: IDA Pro 7.7
Challenge: dreamland (the patched version)
Function: 0x1349
Action: Sync

**Comment by mahaloz** [comment]
[patched_encryptor.zip](https://github.com/angr/binsync/files/8312102/patched_encryptor.zip)
This is the binary from Zer0pts CTF 2022
