### ISSUE TITLE
Binja syncing results in SyntaxError

### ISSUE THREAD

**Issue by Lukas-Dresel** [angr/binsync#121]
Open `phonebook` in binja, go to the `runner` function, hit `sync` on `honululu`'s version

```UI threads are not permitted to wait for analysis completion.
Traceback (most recent call last):
  File "/home/honululu/lukas/tools/binsync/binsync/common/ui/tables/ctx_table.py", line 110, in <lambda>
    menu.addAction("Sync", lambda: self.controller.fill_function(func_addr, user=username))
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 26, in initcheck
    return f(self, *args, **kwargs)
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 93, in state_check
    return f(self, *args, **kwargs)
  File "/home/honululu/.binaryninja/plugins/binja_binsync/controller.py", line 158, in fill_function
    type_, _ = bn_func.view.parse_type_string(stack_var.type)
  File "/home/honululu/lukas/tools/binja/binaryninja/plugins/../python/binaryninja/binaryview.py", line 6173, in parse_type_string
    raise SyntaxError(error_str)
SyntaxError: input:1: error: syntax error
```

**Comment by Lukas-Dresel** [comment]
It looks like the erroring type string is `unsigned __int64`. How is the translation between the tools handled?

**Comment by mahaloz** [comment]
There is actually no way right now since most translations are done on the plugin level. This needs to be changed to the core level. Could be done in maybe a weekend since we have designed the system to support this from the beginning. Big enough to be a major number change though in the version.

**Comment by mahaloz** [comment]
Now tracked in #125
