### ISSUE TITLE
No module named 'binsync.common.ui.magic_sync_dialog'

### ISSUE THREAD

**Issue by P4nda0s** [angr/binsync#149]
C:\Tools\Tools\ida7.7\plugins\ida_binsync.py: Traceback (most recent call last):
  File "C:/Tools/Tools/ida7.7/plugins/ida_binsync.py", line 2, in PLUGIN_ENTRY
    from ida_binsync.plugin import BinsyncPlugin
  File "C:/Tools/Tools/ida7.7/plugins\ida_binsync\plugin.py", line 24, in <module>
    from binsync.common.ui.magic_sync_dialog import display_magic_sync_dialog
ModuleNotFoundError: No module named 'binsync.common.ui.magic_sync_dialog'

I already installed 'binsync' via pip

**Comment by P4nda0s** [comment]
The pip repo is not newest version, so i just copy binsync from git repo to package path.
